CREATE TABLE IF NOT EXISTS analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key TEXT NOT NULL,
    user_id TEXT,
    event_name TEXT NOT NULL CHECK (length(event_name) > 0 AND length(event_name) <= 80),
    source TEXT NOT NULL DEFAULT '',
    target_type TEXT NOT NULL DEFAULT '',
    target_id TEXT NOT NULL DEFAULT '',
    page_path TEXT NOT NULL DEFAULT '',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_analytics_events_created_at ON analytics_events(created_at);

CREATE INDEX IF NOT EXISTS idx_analytics_events_event_name ON analytics_events(event_name, created_at);

CREATE INDEX IF NOT EXISTS idx_analytics_events_source ON analytics_events(source, created_at);

CREATE INDEX IF NOT EXISTS idx_analytics_events_target ON analytics_events(target_type, target_id, created_at);

CREATE INDEX IF NOT EXISTS idx_analytics_events_session ON analytics_events(session_key, created_at);
