use crate::report::{Finding, Report};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

const KNOWN_SECRET_KEYS: &[&str] = &[
    "APP_ENV",
    "PUBLIC_BASE_URL",
    "DATABASE_URL",
    "SESSION_SECRET",
    "NEON_API_KEY",
    "RAILWAY_TOKEN",
    "STRIPE_SECRET_KEY",
    "STRIPE_WEBHOOK_SECRET",
];

pub fn import_email(root: &Path, from: &str, apply: bool) -> Result<Report, String> {
    let source = root.join(from);
    let contents = fs::read_to_string(&source)
        .map_err(|err| format!("failed to read secrets source {}: {err}", source.display()))?;
    let parsed = parse_known_secrets(&contents);

    let mut report = Report::new("external.secrets.import_email");
    if parsed.is_empty() {
        report.findings.push(Finding::fail(
            "secrets.import_email",
            "secrets",
            "empty",
            "No known secret keys were found in the provided text.",
            &source.display().to_string(),
            "no_known_secrets_found",
            "Add KEY=value lines for known demo keys, then rerun import-email.",
        ));
        return Ok(report);
    }

    report.findings.push(Finding::info(
        "secrets.import_email",
        "secrets",
        "parsed",
        &format!("Parsed {} known secret keys.", parsed.len()),
        &parsed
            .keys()
            .map(|key| format!("{key}=<redacted>"))
            .collect::<Vec<_>>()
            .join(", "),
    ));

    if apply {
        let target = root.join("setup/.secrets.demo.env");
        let mut output = String::new();
        output.push_str("# Generated by `cargo xtask external secrets import-email --yes`.\n");
        output.push_str("# Do not commit this file.\n\n");
        for (key, value) in parsed {
            output.push_str(&key);
            output.push('=');
            output.push_str(&quote_env_value(&value));
            output.push('\n');
        }
        fs::write(&target, output)
            .map_err(|err| format!("failed to write {}: {err}", target.display()))?;
        report.findings.push(Finding::ok(
            "secrets.import_email.write",
            "secrets",
            "written",
            "Wrote parsed demo secrets to setup/.secrets.demo.env.",
            "Values redacted.",
        ));
    } else {
        report.findings.push(Finding::warn(
            "secrets.import_email.write",
            "secrets",
            "dry_run",
            "Parsed secrets were not written because --yes was not passed.",
            "Rerun with `cargo xtask external secrets import-email --from <file> --yes` to write setup/.secrets.demo.env.",
        ));
    }

    Ok(report)
}

pub fn parse_known_secrets(contents: &str) -> BTreeMap<String, String> {
    let mut parsed = BTreeMap::new();

    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        for key in KNOWN_SECRET_KEYS {
            if let Some(value) = parse_line_value(line, key) {
                parsed.insert((*key).to_string(), value);
            }
        }
    }

    parsed
}

fn parse_line_value(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?;
    let rest = rest.trim_start();
    let value = if let Some(value) = rest.strip_prefix('=') {
        value
    } else {
        rest.strip_prefix(':')?
    };

    let value = value.trim().trim_matches('"').trim_matches('\'');
    (!value.is_empty()).then(|| value.to_string())
}

fn quote_env_value(value: &str) -> String {
    if value.chars().all(|ch| {
        ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.' | '/' | ':' | '?' | '&' | '=')
    }) {
        value.to_string()
    } else {
        format!("\"{}\"", value.replace('"', "\\\""))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_known_key_value_and_colon_lines() {
        let parsed = parse_known_secrets(
            "hello\nDATABASE_URL=postgres://demo\nSESSION_SECRET: very-secret\nUNKNOWN=value\n",
        );

        assert_eq!(parsed.get("DATABASE_URL").unwrap(), "postgres://demo");
        assert_eq!(parsed.get("SESSION_SECRET").unwrap(), "very-secret");
        assert!(!parsed.contains_key("UNKNOWN"));
    }

    #[test]
    fn quotes_values_with_spaces() {
        assert_eq!(quote_env_value("abc-123"), "abc-123");
        assert_eq!(quote_env_value("abc 123"), "\"abc 123\"");
    }
}
